Models/Message.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Property_Rental_Management_Web_Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageID { get; set; }
        public Nullable<int> ApartmentID { get; set; }
        public int SenderID { get; set; }
        public int RecieverID { get; set; }
        public System.DateTime Date { get; set; }
        public string Text { get; set; }
    
        public virtual Apartment Apartment { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}

Controllers/MessagesController.cs
using Property_Rental_Management_Web_Site.Models;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace Property_Rental_Management_Web_Site.Controllers {
	public class MessagesController: Controller {
		private readonly PropertyRentalDBEntities db = new PropertyRentalDBEntities();

		// GET: Messages
		public ActionResult Index() {
			using (PropertyRentalDBEntities context = new PropertyRentalDBEntities()) {
				var user = context.Users.FirstOrDefault(u => u.Email == User.Identity.Name);
				ViewBag.Username = user.FirstName + " " + user.LastName;
			}
			var messages = db.Messages.Include(m => m.Apartment).Include(m => m.User).Include(m => m.User1);
			return View(messages.ToList());
		}

		// GET: Messages/Details/5
		public ActionResult Details(int? id) {
			if (id == null) {
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Message message = db.Messages.Find(id);
			if (message == null) {
				return HttpNotFound();
			}
			return View(message);
		}

		// GET: Messages/Create
		public ActionResult Create() {
			ViewBag.ApartmentID = new SelectList(db.Apartments, "ApartmentID", "Extra");
			ViewBag.RecieverID = new SelectList(db.Users, "UserID", "FirstName");
			ViewBag.SenderID = new SelectList(db.Users, "UserID", "FirstName");
			return View();
		}

		// POST: Messages/Create
		// To protect from overposting attacks, enable the specific properties you want to bind to, for 
		// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create([Bind(Include = "MessageID,ApartmentID,SenderID,RecieverID,Date,Text")] Message message) {
			if (ModelState.IsValid) {
				db.Messages.Add(message);
				db.SaveChanges();
				return RedirectToAction("Index");
			}

			ViewBag.ApartmentID = new SelectList(db.Apartments, "ApartmentID", "Extra", message.ApartmentID);
			ViewBag.RecieverID = new SelectList(db.Users, "UserID", "FirstName", message.RecieverID);
			ViewBag.SenderID = new SelectList(db.Users, "UserID", "FirstName", message.SenderID);
			return View(message);
		}

		// GET: Messages/Edit/5
		public ActionResult Edit(int? id) {
			if (id == null) {
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Message message = db.Messages.Find(id);
			if (message == null) {
				return HttpNotFound();
			}
			ViewBag.ApartmentID = new SelectList(db.Apartments, "ApartmentID", "ApartmentID", message.ApartmentID);
			ViewBag.RecieverID = new SelectList(db.Users, "UserID", "UserID", message.RecieverID);
			ViewBag.SenderID = new SelectList(db.Users, "UserID", "UserID", message.SenderID);
			return View(message);
		}

		// POST: Messages/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to, for 
		// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit([Bind(Include = "MessageID,ApartmentID,SenderID,RecieverID,Date,Text")] Message message) {
			if (ModelState.IsValid) {
				db.Entry(message).State = EntityState.Modified;
				db.SaveChanges();
				return RedirectToAction("Index");
			}
			ViewBag.ApartmentID = new SelectList(db.Apartments, "ApartmentID", "ApartmentID", message.ApartmentID);
			ViewBag.RecieverID = new SelectList(db.Users, "UserID", "UserID", message.RecieverID);
			ViewBag.SenderID = new SelectList(db.Users, "UserID", "UserID", message.SenderID);
			return View(message);
		}

		// GET: Messages/Delete/5
		public ActionResult Delete(int? id) {
			if (id == null) {
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Message message = db.Messages.Find(id);
			if (message == null) {
				return HttpNotFound();
			}
			return View(message);
		}

		// POST: Messages/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public ActionResult DeleteConfirmed(int id) {
			Message message = db.Messages.Find(id);
			db.Messages.Remove(message);
			db.SaveChanges();
			return RedirectToAction("Index");
		}

		protected override void Dispose(bool disposing) {
			if (disposing) {
				db.Dispose();
			}
			base.Dispose(disposing);
		}

		public ActionResult MyMessages() {
			// Check if the user is authenticated
			if (User.Identity.IsAuthenticated) {
				// Get the email of the currently logged-in user
				string userEmail = User.Identity.Name;

				List<Message> userMessages;
				using (PropertyRentalDBEntities context = new PropertyRentalDBEntities()) {
					var user = context.Users.FirstOrDefault(u => u.Email == User.Identity.Name);
					ViewBag.Username = user.FirstName + " " + user.LastName;
					// Explicitly include the related User, User1, and Apartment entities
					userMessages = context.Messages
							.Include(m => m.User)
							.Include(m => m.User1)
							.Include(m => m.Apartment.Address)
							.Where(m => m.User.Email == userEmail || m.User1.Email == userEmail)
							.ToList();
				}

				return View(userMessages);
			} else {
				// Handle the case when the user is not authenticated
				// You might want to redirect them to the login page or take other actions.
				return RedirectToAction("Login", "Login");
			}
		}

	}
}

Controllers/TenantController.cs
using Property_Rental_Management_Web_Site.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Property_Rental_Management_Web_Site.Controllers {
	public class TenantController: Controller {
		// GET: Tenant
		public ActionResult Index() {
			List<Apartment> apartments;
			using (PropertyRentalDBEntities context = new PropertyRentalDBEntities()) {
				apartments = context.Apartments.Include("Address").Where(a => a.Status == "Available").ToList();
				var user = context.Users.FirstOrDefault(u => u.Email == User.Identity.Name);
				ViewBag.Username = user.FirstName + " " + user.LastName;
			}

			return View(apartments);
		}





		// GET: WriteMessage
		public ActionResult WriteMessage(int id) {
			var message = new Message { ApartmentID = id };

			using (PropertyRentalDBEntities context = new PropertyRentalDBEntities()) {
				var user = context.Users.FirstOrDefault(u => u.Email == User.Identity.Name);
				ViewBag.Username = user.FirstName + " " + user.LastName;
			}

			return View(message);
		}


		// POST: WriteMessage
		[HttpPost]
		public ActionResult WriteMessage(Message msg, int id) {
			try {
				// Get the sender (logged-in user)
				string senderEmail = User.Identity.Name;
				User sender = null;
				using (PropertyRentalDBEntities context = new PropertyRentalDBEntities()) {
					sender = context.Users.FirstOrDefault(u => u.Email == senderEmail);
				}

				// Get the receiver (user associated with the specified apartment)
				User receiver = null;
				using (PropertyRentalDBEntities context = new PropertyRentalDBEntities()) {
					var apartment = context.Apartments
													.Where(a => a.ApartmentID == id);
					receiver = apartment.Select(a => a.User).FirstOrDefault();
				}

				// Create a new message
				Message message = new Message {
					ApartmentID = id,
					SenderID = sender.UserID,
					RecieverID = receiver.UserID,
					Date = DateTime.Now,
					Text = msg.Text
				};

				// Add the message to the database
				using (PropertyRentalDBEntities context = new PropertyRentalDBEntities()) {
					context.Messages.Add(message);
					context.SaveChanges();
				}

				return RedirectToAction("MyMessages", "Messages"); // Redirect to the user's messages page
			} catch (Exception ex) {
				// Log the exception or handle it as needed
				Debug.WriteLine("Error saving message: " + ex.Message);
				// You can also return an error view or message to the user
				return View("Error");
			}
		}





		// GET: MakeAppointment
		public ActionResult MakeAppointment(int id) {
			var appointment = new Appointment { ApartmentID = id, Date = DateTime.Today };

			using (PropertyRentalDBEntities context = new PropertyRentalDBEntities()) {
				var user = context.Users.FirstOrDefault(u => u.Email == User.Identity.Name);
				ViewBag.Username = user.FirstName + " " + user.LastName;
			}

			return View(appointment);
		}


		// POST: MakeAppointment
		[HttpPost]
		public ActionResult MakeAppointment(Appointment app, int id) {
			Debug.WriteLine("Date and Time: " + app.Date.ToString());
			// Get the logged-in user
			string userEmail = User.Identity.Name;
			User user = null;
			using (PropertyRentalDBEntities context = new PropertyRentalDBEntities()) {
				user = context.Users.FirstOrDefault(u => u.Email == userEmail);
			}

			// Get the associated apartment
			Apartment apartment = null;
			using (PropertyRentalDBEntities context = new PropertyRentalDBEntities()) {
				apartment = context.Apartments.FirstOrDefault(a => a.ApartmentID == id);
			}

			if (user != null && apartment != null) {
				if (app.Date > DateTime.Now) {
					// Create a new appointment with status "Pending"
					Appointment appointment = new Appointment {
						ApartmentID = id,
						ManagerID = apartment.ManagerID,
						TenantID = user.UserID,
						Date = app.Date,
						Status = "Pending" // Set status to "Pending"
					};

					// Add the appointment to the database
					using (PropertyRentalDBEntities context = new PropertyRentalDBEntities()) {
						context.Appointments.Add(appointment);
						context.SaveChanges();
					}

					return RedirectToAction("MyAppointments", "Appointments"); // Redirect to the user's appointments page
				} else {
					// Handle the case where the appointment date is not in the future
					ViewBag.ErrorMessage = "Appointment date must be in the future.";
					return View("Error");
				}
			} else {
				// Handle the case where user or apartment is not found
				return View("Error");
			}
		}

	}
}

Views/Messages/Create.cshtml
@model Property_Rental_Management_Web_Site.Models.Message

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Message</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ApartmentID, "Apartment ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ApartmentID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ApartmentID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SenderID, "Sender ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SenderID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SenderID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RecieverID, "Recipient ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RecieverID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RecieverID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Messages/Delete.cshtml
@model Property_Rental_Management_Web_Site.Models.Message

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Message</h4>
    <hr />
		<dl class="dl-horizontal">
			<dt>
				@Html.DisplayNameFor(model => model.Date)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.Date)
			</dd>

			<dt>
				Apartment ID
			</dt>

			<dd>
				@Html.DisplayFor(model => model.Apartment.ApartmentID)
			</dd>

			<dt>
				Sender
			</dt>

			<dd>
				@Html.DisplayFor(model => model.User1.FirstName)
				@Html.DisplayFor(model => model.User1.LastName)
			</dd>

			<dt>
				Recipient
			</dt>

			<dd>
				@Html.DisplayFor(model => model.User.FirstName)
				@Html.DisplayFor(model => model.User.LastName)
			</dd>

			<dt>
				@Html.DisplayNameFor(model => model.Text)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.Text)
			</dd>

		</dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Messages/Details.cshtml
@model Property_Rental_Management_Web_Site.Models.Message

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Message</h4>
    <hr />
		<dl class="dl-horizontal">
			<dt>
				@Html.DisplayNameFor(model => model.Date)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.Date)
			</dd>

			<dt>
				Apartment ID
			</dt>

			<dd>
				@Html.DisplayFor(model => model.Apartment.ApartmentID)
			</dd>

			<dt>
				Sender
			</dt>

			<dd>
				@Html.DisplayFor(model => model.User1.FirstName)
				@Html.DisplayFor(model => model.User1.LastName)
			</dd>

			<dt>
				Recipient
			</dt>

			<dd>
				@Html.DisplayFor(model => model.User.FirstName)
				@Html.DisplayFor(model => model.User.LastName)
			</dd>

			<dt>
				@Html.DisplayNameFor(model => model.Text)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.Text)
			</dd>

		</dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MessageID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Messages/Edit.cshtml
@model Property_Rental_Management_Web_Site.Models.Message

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
	<h4>Message</h4>
	<hr />
	@Html.ValidationSummary(true, "", new { @class = "text-danger" })
	@Html.HiddenFor(model => model.MessageID)

	<div class="form-group">
		@Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.ApartmentID, "Apartment ID", htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.DropDownList("ApartmentID", null, htmlAttributes: new { @class = "form-control" })
			@Html.ValidationMessageFor(model => model.ApartmentID, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.SenderID, "Sender ID", htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.DropDownList("SenderID", null, htmlAttributes: new { @class = "form-control" })
			@Html.ValidationMessageFor(model => model.SenderID, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.RecieverID, "Recipient ID", htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.DropDownList("RecieverID", null, htmlAttributes: new { @class = "form-control" })
			@Html.ValidationMessageFor(model => model.RecieverID, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		<div class="col-md-offset-2 col-md-10">
			<input type="submit" value="Save" class="btn btn-default" />
		</div>
	</div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Messages/Index.cshtml
@model IEnumerable<Property_Rental_Management_Web_Site.Models.Message>

@{
	ViewBag.Title = "Index";
}

<h3>Welcome - @ViewBag.Username</h3>
<h5>All Messages:</h5>

@*<p>
			@Html.ActionLink("Create New", "Create")
	</p>*@
<table class="table">
	<tr>
		<th>
			@Html.DisplayNameFor(model => model.Date)
		</th>
		<th>
			Apartment ID
		</th>
		<th>
			Sender
		</th>
		<th>
			Recipient
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Text)
		</th>
	</tr>

	@foreach (var item in Model) {
		<tr>
			<td>
				@Html.DisplayFor(modelItem => item.Date)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Apartment.ApartmentID)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.User1.FirstName)
				@Html.DisplayFor(modelItem => item.User1.LastName)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.User.FirstName)
				@Html.DisplayFor(modelItem => item.User.LastName)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Text)
			</td>
			<td>
				@Html.ActionLink("Edit", "Edit", new { id = item.MessageID }) |
				@Html.ActionLink("Details", "Details", new { id = item.MessageID }) |
				@Html.ActionLink("Delete", "Delete", new { id = item.MessageID })
			</td>
		</tr>
	}

</table>

Views/Messages/MyMessages.cshtml
@model IEnumerable<Property_Rental_Management_Web_Site.Models.Message>

@{
	ViewBag.Title = "My Messages";
	Layout = null;
}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@ViewBag.Title - My ASP.NET Application</title>
	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/modernizr")
</head>
<body>
	<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
		<div class="container">
			<div class="navbar-brand">Property Rental</div>
			<button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
							aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
				<ul class="navbar-nav flex-grow-1">
					<li>@Html.ActionLink("Apartments", "Index", "Tenant", new { area = "" }, new { @class = "nav-link" })</li>
					<li>@Html.ActionLink("Messages", "MyMessages", "Messages", new { area = "" }, new { @class = "nav-link" })</li>
					<li>@Html.ActionLink("Appointments", "MyAppointments", "Appointments", new { area = "" }, new { @class = "nav-link" })</li>
				</ul>
				<ul class="nav nav-pills nav-fill">
					<li>@Html.ActionLink("Logout", "Login", "Login", new { area = "" }, new { @class = "nav-link active" })</li>
				</ul>
			</div>
		</div>
	</nav>
	<div class="container body-content">
		<main>
			<h3>Welcome - @ViewBag.Username</h3>
			<h5>My Messages:</h5>

			<table class="table">
				<thead>
					<tr>
						<th>Date</th>
						<th>Address</th>
						<th>Sender</th>
						<th>Recipient</th>
						<th>Text</th>
					</tr>
				</thead>
				<tbody>
					@foreach (var message in Model) {
						<tr>
							<td>@message.Date</td>
							<td>
								@message.Apartment.Address.Street, 
								@message.Apartment.Address.Unit, 
								@message.Apartment.Address.ZipCode, 
								@message.Apartment.Address.City
							</td>
							<td>
								@message.User1.FirstName
								@message.User1.LastName
							</td>
							<td>
								@message.User.FirstName
								@message.User.LastName
							</td>
							<td>@message.Text</td>
						</tr>
					}
				</tbody>
			</table>

		</main>
		<div class="container body-content">
			<hr />
			<footer>
				<p>&copy; @DateTime.Now.Year - Property Rental Website</p>
			</footer>
		</div>
	</div>
</body>
</html>